---

avr:
    type: yamaha  # yamaha or pioneer
    host: 192.168.0.123"
temperature:
    id: "28-80000028c9b1" # ID of DS18B20
    interval: 30000
lcd:
    device: "/dev/i2c-1"
    address: 0x27
encoder:
    leftPin: 5
    rightPin: 6
    buttonPin: 26
    factor: 4 # must turn this many notches to up the volume
